spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpadb;MVCC=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${ACCESS_ID}
    password: ${ACCESS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
